keywords_list = [
    "Show me open roles",
    "See job openings",
    "Search Jobs",
    "Find Jobs",
    "Apply Now",
    "Submit Application",
    "View Openings",
    "Browse Vacancies",
    "Search Careers",
    "Job Listings",
    "Explore Opportunities",
    "See All Jobs",
    "View All Positions",
    "Open Roles",
    "Current Vacancies",
    "Discover Careers",
    "Job Opportunities",
    "Start Your Journey",
    "Find Your Role",
    "Join Us",
    "Job Search",
    "Search Vacancies",
    "Recruitment",
    "Begin Here",
    "Apply Today",
    "Hiring Now",
    "Work With Us",
    "Available Positions",
    "See Open Roles",
    "Join Our Team",
    "See Vacancies",
    "Career Opportunities",
    "Immediate Openings",
    "Submit CV",
    "Post Your CV",
    "Upload Resume",
    "Find Your Job",
    "Job Alerts",
    "New Openings",
    "Get Hired",
    "Current Openings",
    "Current Opportunities",
    "Apply Online",
    "Quick Apply",
    "Search for Roles",
    "Join Now",
    "Find Work",
    "Career Search",
    "Upload CV",
    "Your Next Step",
    "Find Employment",
    "See Job Listings",
    "Look for Jobs",
    "Browse Roles",
    "Job Board",
    "Open Positions",
    "Uncover Opportunities",
    "Check Vacancies",
    "Search Now",
    "Latest Jobs",
    "Today's Jobs",
    "Explore Careers",
    "Find Positions",
    "View Jobs",
    "Ready to Apply",
    "Let's Go",
    "Apply Here",
    "Find a Job",
    "Seek Opportunities",
    "Recent Openings",
    "Career Path",
    "Work Opportunities",
    "Get Recruited",
    "View Career Options",
    "Find Your Fit",
    "Submit Your Application",
    "Join the Team",
    "Become a Member",
    "Start Application",
    "See Available Jobs",
    "Browse Job Listings",
    "Submit Resume",
    "Ready to Work",
    "Inquire Within",
    "Job Offers",
    "Search Openings",
    "Go For It",
    "Show Jobs",
    "Start Now",
    "Act Now",
    "Join the Crew",
    "Seeking Candidates",
    "Hunt Jobs",
    "Look for Vacancies",
    "Open Job Listings",
    "Live Jobs",
    "Apply Within",
    "Career Finder",
    "Ready to Join",
    "Positions Open",
    "Join Today",
    "Enquire Now",
    "Job Board Listings",
    "Discover Jobs",
    "See Career Options",
    "Start Your Career",
    "Your Next Job",
    "Apply and Join",
    "View Latest Jobs",
    "Submit Enquiry",
    "Ready to Start",
    "Hiring Immediately",
]
